### ISSUE TITLE
Marketplace button

### ISSUE THREAD

**Issue by NettoSpaghetto** [Lunaversitay/crident.store#11]
For the marketplace button, it would be good if you could make clicking on it also bring you to the marketplace instead of having to select an option underneath it.

**Comment by Lunaversitay** [comment]
I'll look into this a bit later, atm it tries but bootstrap on some browsers doesn't let it. Probably will end up using JS or something.

**Comment by Lunaversitay** [comment]
Fixed in the next update, thanks. https://cdn.discordapp.com/attachments/503390051879878666/547312019997458432/YTMyIWUMPb.gif
