### ISSUE TITLE
Discounting products

### ISSUE THREAD

**Issue by 0wain** [Lunaversitay/crident.store#13]
**Describe the bug**
When trying to discount an already posted product, there is still a $5 limit. However, discounting a product on its initial purchase seems to have no discount limit?
That being said, I was also able to discount my script to $0 on initial submission.

**Comment by Lunaversitay** [comment]
Yeah, I saw the $0 discount issue, I've solved that in the next update.

As for the $5 limit on editing, its most likely the front-end validation I forgot to patch up, so that'll also be fixed in the next update.

**Comment by Lunaversitay** [comment]
This has been fixed in the next update, thanks.
