### ISSUE TITLE
Filter Bug

### ISSUE THREAD

**Issue by ArchieeR** [Lunaversitay/crident.store#15]
**Describe the bug**
Filter on the main page doesn't work

**To Reproduce**
1. Go to main page
2. Click on Filter
3. Choose Tem Fortress or Gmod
4. Just doesn't work

**Expected behavior**
I'm guessing it is supposed to only show addons from the selected game

**Screenshots**
https://i.imgur.com/g1pZo66.png

**Comment by Lunaversitay** [comment]
This is fixed in the next update, filter wasn't really meant to do anything atm since we have no real categories up.
