### ISSUE TITLE
Dashboard button

### ISSUE THREAD

**Issue by Rhyss-me** [Lunaversitay/crident.store#3]
Is the Dashboard button once you click on Profile Settings meant to do something, because it doesn't.
![e1163e](https://user-images.githubusercontent.com/37268137/50446549-4518f880-090d-11e9-9356-5ea28f84bc53.png)

You probably already have this down but i couldn't see it anywhere.

**Comment by Lunaversitay** [comment]
Dashboard doesn't go anywhere cause there's nothing to really display atm
