### ISSUE TITLE
Product page suggestions

### ISSUE THREAD

**Issue by LiamD-Flop** [Lunaversitay/crident.store#4]
So in the product page I saw the image not fitting the box you made for it,
I suggest using `object-fit: cover or contain;` (Cover will cut away part of the image & contain will make the image fit within the dimentions given).

I'd also suggest adding a top review to the page (just a suggestions, this isn't necessary) If you'd add this I would suggest adding `overflow-y: scroll;` to the team section to not add unnecessary height to the page

And maybe add some `<hr>` or `border` between the product information and the team

![suggestion](https://user-images.githubusercontent.com/40887493/50446655-6a5e3480-0916-11e9-959d-a48f82b5221a.png)

**Comment by Lunaversitay** [comment]
I'm not sure what you mean by the image not fitting? It looks like its fitting as intended.

Yeah, we're thinking about adding either builds or reviews to that whitespaced area, or maybe both, who knows!

**Comment by Lunaversitay** [comment]
I read you wrong, I see the thing about the product banner, I'm looking into solutions for it.

**Comment by Lunaversitay** [comment]
Thanks for the suggestion, its been added in one of the updates.
