### ISSUE TITLE
"Your email must be verified before you can continue" screen before email has been set

### ISSUE THREAD

**Issue by WilliamVenner** [Lunaversitay/crident.store#6]
**Describe the bug**
The "Your email must be verified before you can continue" screen appears before an email on the user's account has even been set, therefore, clicking the "Resend Verification Email" does nothing

**To Reproduce**
1. New account
2. Do not set an email
3. https://crident.store/email/required

**Expected behavior**
The email would be sent

**Screenshots**
http://i.venner.io/chrome_2018-12-26_17-25-13.png

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 71.0.3578.98 (Official Build) (64-bit)

**Comment by WilliamVenner** [comment]
Users without emails should be redirected to https://crident.store/email/new instead

**Comment by Lunaversitay** [comment]
While designing the new system for new users I found that out and fixed it, it'll be fixed in the next update!
